In [ ]:
# !pip install pymysql
# !pip install sqlalchemy

In [ ]:
from src.my_functions import analysis_functions as mybib
from src.my_functions import lab_functions as lab

import pandas as pd 
import numpy as np 

import pymysql 
from sqlalchemy import create_engine
from getpass import getpass  

%load_ext autoreload
%autoreload 2

# Checklist 

- [x] get data
- [x] check and clean data (nulls, fixing typos, outliers, distrubutions,...)
- [x] data exploration
- [x] select features
- [x] check for multicolinearity
- [ ] X/y split (feature/target) : X, y
- [ ] train/test split : X_train, X_test, y_train, y_test
- [ ] num/cat split : X_train_num, X_train_cat, X_test_num, X_test_cat
- [ ] fit transformer on X_train_num
- [ ] run transformer on X_train_num : X_train_normalized
- [ ] run same transformer on X_test_num : X_test_normalized
- [ ] fit encoder on X_train_cat
- [ ] run encoder on X_train_cat : X_train_encoded
- [ ] run same encoder on X_test_cat : X_test_encoded
- [ ] concat X_train_normalized and X_train_encoded : X_train_transformed
- [ ] choose model (LienarRegression on numeric target, LogisticRegression(=classification!) on categorical target)
- [ ] fit (train) model in X_train_transformed : model
- [ ] concat X_test_normalized and X_test_encoded : X_test_transformed
- [ ] make predictions using X_test_transfomed : model.predict -> predictions
- [ ] compute score using predictions and y_test

In [ ]:
# Establish a connection between Python and the Sakila database.

password = getpass()

connection_string = 'mysql+pymysql://root:'+password+'@localhost/sakila'
engine = create_engine(connection_string)

In [ ]:
## Version 1 
query = '''
SELECT f.title as film_title, c.name, f.rental_duration, f.rental_rate, f.rating, f.length, f.replacement_cost, count(DISTINCT r.rental_id) AS rental_count, count(DISTINCT r.inventory_id) AS inventory_count, 
    CASE
        WHEN EXISTS (SELECT 1 FROM (SELECT DISTINCT f.title
                                    FROM film f
                                    JOIN inventory i USING (film_id)
                                    JOIN rental r USING (inventory_id)
                                    WHERE r.rental_date LIKE '2005-05%%')may where may.title = f.title) THEN 'Yes'
        ELSE 'No'
    END AS check_may
FROM film f
LEFT JOIN inventory i USING (film_id)
LEFT JOIN rental r USING (inventory_id)
LEFT JOIN film_category fc USING (film_id)
JOIN category c USING (category_id)
GROUP BY f.film_id, c.name;
'''


df = pd.read_sql_query(query, engine)
df.to_csv('data\output.query1')

In [ ]:
## Version 2 
query = '''
SELECT f.title as film_title, c.name, f.rental_duration, f.rental_rate, f.rating, f.length, f.replacement_cost, COUNT(DISTINCT fa.actor_id) AS actor_count, count(DISTINCT r.rental_id) AS rental_count, count(DISTINCT r.inventory_id) AS inventory_count, 
    CASE
        WHEN EXISTS (SELECT 1 FROM (SELECT DISTINCT f.title
                                    FROM film f
                                    JOIN inventory i USING (film_id)
                                    JOIN rental r USING (inventory_id)
                                    WHERE r.rental_date LIKE '2005-05%%')may where may.title = f.title) THEN 'Yes'
        ELSE 'No'
    END AS check_may
FROM film f
LEFT JOIN inventory i USING (film_id)
LEFT JOIN rental r USING (inventory_id)
LEFT JOIN film_category fc USING (film_id)
LEFT JOIN film_actor fa USING (film_id)
JOIN category c USING (category_id)
GROUP BY f.film_id, c.name;
'''


df = pd.read_sql_query(query, engine)
display(df)
df.to_csv('data\output.query2')

In [ ]:
# Option to run different queries for trying different versions of features

In [219]:
film1 = pd.read_csv('data\output.query1', index_col=0)
film2 = pd.read_csv('data\output.query2',index_col=0)

In [ ]:
## Used to discover data
# mybib.firstLook(film1)
# lab.discover_df(film1)

In [225]:
# With rental_count USING logisticRegression

film1_v1 = film1.drop('film_title', axis = 1 )
predictions, y_train = lab.split_encode_use_logisticRegression(film1_v1)
# print(predictions)
# print(y_train)

Model Score for Train = 0.81125
Model Score for Test = 0.8
[[ 39  28]
 [ 12 121]]


In [221]:
# Without rental_count USING logisticRegression

film1_v2 = film1.drop(['rental_count', 'film_title'], axis = 1 )
predictions, y_train = lab.split_encode_use_logisticRegression(film1_v2)

Model Score for Train = 0.74125
Model Score for Test = 0.745
[[ 24  34]
 [ 17 125]]


In [222]:
# Without rental_count USING neighbors
predictions, y_train = lab.split_encode_use_neighbors(film1_v2)

Model Score for Train = 0.80125
Model Score for Test = 0.575
[[ 13  52]
 [ 33 102]]
